web:                                                                                                                                                                                                                                        
  image: 'gitlab/gitlab-ce:14.3.4-ce.0'                                                                                                                                                                                                     
  restart: always                                                                                                                                                                                                                           
  hostname: 'YOURDOMAINHERE'                                                                                                                                                                                                           
  links:                                                                                                                                                                                                                                    
    - mailserver                                                                                                                                                                                                                            
  environment:                                                                                                                                                                                                                              
    GITLAB_OMNIBUS_CONFIG: |                                                                                                                                                                                                                
      external_url 'http://127.0.0.1'                                                                                                                                                                                                       
      # Add any other gitlab.rb configuration here, each on its own line
      nginx['redirect_http_to_https'] = false
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      gitlab_rails['ssh_host'] = 'YOURDOMAINHERE'
      gitlab_rails['gitlab_host'] = 'YOURDOMAINHERE'
      letsencrypt['enable'] = false
      prometheus['monitor_kubernetes'] = false
      gitlab_rails['backup_path'] = '/var/backups'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "mailserver"
      gitlab_rails['smtp_port'] = 587
  ports:
    - 'OUTWARDHTTPPORT:80'
    - 'OUTWARDSSLPORT:443'
    - 'ANOTHERPORT:22'
  volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
    - './backups:/var/backups'

