version: '3'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "8091:8080"
    - "50000:50000"
    environment:
    - JENKINS_OPTS="--prefix=/"
    volumes:
    - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

